### ISSUE TITLE
expand motif search

### ISSUE THREAD

**Issue by pettestor** [ra7555ga-s/UniStem2020#1]
I like the motif part! What if we make it a little bit more tricky? Let's say that the motif does not actually match perfectly with the reference sequence (which is of course what usually happens IRL)? How would you go about solving the problem?

I dont think reimplementing the smith waterman algorithm would be feasible for 30 minutes :)
I suggest that they split the query sequence into kmers and try to see if they can match these with the reference?

**Comment by raquelgarza** [comment]
Thanks for the idea! I just added it :).

**Comment by pettestor** [comment]
Smashing!
